// <auto-generated />
using CoreAutomotive.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreAutomotive.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191022211538_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("CoreAutomotive.Models.Samochod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<bool>("JestSamochodemTygodnia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("JestWCentrali")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marka")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiniaturkaUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pojemnosc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Przebieg")
                        .HasColumnType("TEXT");

                    b.Property<string>("RodzajPaliwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RokProdukcji")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZdjecieUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Samochody");
                });
#pragma warning restore 612, 618
        }
    }
}
